version: "3.9"
services:
  postgres:
    image: postgres:13-alpine
    restart: always
    environment:
      POSTGRES_DB: RoycemoreBotDB
      POSTGRES_PASSWORD: Griffin1
      POSTGRES_USER: RoycemoreBot
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  bot:
    build: .
    restart: always
    volumes:
      - ./logs:/bot/logs
      - .:/bot:ro
    tty: true
    depends_on:
      - postgres
    env_file:
      - .env
    environment:
      DATABASE_URL: postgres://RoycemoreBot:Griffin1@postgres:5432/RoycemoreBotDB

volumes:
  pgdata:
